baseURL = "https://harveykandola.com/"
languageCode = "en-us"
title = "Harvey Kandola"
theme = "hyde-hyde"
enableRobotsTXT = true
enableGitInfo = true

[params]
    authorimage = "/hsk.jpg"
    description = "tech // startups // misc."
    author = "Harvey Kandola"
    copyright = "© 2018"
    dateformat = "Jan 2, 2006"
    highlightjs = true
    themeColor= "theme-base-09"

[params.social]
    github = "HarveyKandola"
    linkedin = "HarveyKandola"
    twitter = "HarveyKandola"

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"

[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
